name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: marsselu
          outputs: |
            output/snake-dark.svg?palette=github-dark
            output/snake-light.svg?palette=github-light

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
