name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # executa a cada 12h
  workflow_dispatch:        # permite rodar manualmente

permissions:
  contents: write  # necessário para publicar o resultado

jobs:
  build:
    name: Gerar animação da cobra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar Snake (modo escuro e claro)
        id: snake
        uses: Platane/snk@v3
        with:
          github_user_name: marsselu
          outputs: |
            output/snake-dark.svg?palette=github-dark
            output/snake-light.svg?palette=github-light

      - name: Publicar SVG na branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
